<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeursRepository extends EntityRepository
{
    public function countNbActeurs()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a) FROM TroiswaBackBundle:Acteurs a'
            )
            ->getSingleResult();
    }

    public function countNbHommes()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a) FROM TroiswaBackBundle:Acteurs a WHERE a.sexe = 1'
            )
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function countNbFemmes()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(a) FROM TroiswaBackBundle:Acteurs a WHERE a.sexe = 0'
            )
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function filmographie($id)  {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f.titre FROM TroiswaBackBundle:Acteurs a JOIN a.liaisonFilm f WHERE a.id=:id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }

}
