<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * filmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filmsRepository extends EntityRepository
{
    public function countNbFilms()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(f) FROM TroiswaBackBundle:films f'
            )
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function lastFilms()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f.id, f.titre FROM TroiswaBackBundle:films f ORDER BY f.dateDeRealisation DESC'
            )
            ->setMaxResults(3)
            ->getResult();
    }

    public function genreFilms($genre)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f.id, f.titre FROM TroiswaBackBundle:films f JOIN f.liaisonGenre g WHERE g.type=:genre'
            )
            ->setParameter('genre', $genre)
            ->getResult();
    }

    public function bestFilms()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT f.id, f.titre FROM TroiswaBackBundle:films f ORDER BY f.note DESC'
            )
            ->setMaxResults(1)
            ->getSingleResult();
    }
}
