<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * genreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class genreRepository extends EntityRepository
{
    public function countNbGenres()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u) FROM TroiswaBackBundle:genre u'
            )
            ->getSingleResult();
    }
}
